- name: Include OS-specific variables (Debian/Ubuntu<=15.10).
  include_vars: default.yml
  when: ansible_distribution == 'Debian' or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version != '16' and not php_use_ppa)

- name: Include OS-specific variables (Ubuntu 16.04).
  include_vars: '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16' and not php_use_ppa

- name: Include OS-specific variables (Ubuntu with PPA).
  include_vars: '{{ ansible_distribution }}-ppa.yml'
  when: ansible_distribution == 'Ubuntu' and php_use_ppa

- include: setup.yml
  tags: postgresql
