- name: Include OS-specific variables (Debian).
  include_vars: '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
  when: ansible_distribution == 'Debian'
  tags: postgresql

- name: Include OS-specific variables (Ubuntu).
  include_vars: '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
  when: ansible_distribution == 'Ubuntu' and not php_use_ppa
  tags: postgresql

- name: Include OS-specific variables (Ubuntu with PPA).
  include_vars: '{{ ansible_distribution }}-ppa.yml'
  when: ansible_distribution == 'Ubuntu' and php_use_ppa
  tags: postgresql

- include_tasks: setup.yml
  tags: postgresql
