- name: Add postgreSQL GPG key
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgreSQL debian repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    update_cache: yes
    state: present

- name: Be sure postgreSQL client packages are installed
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ postgresql_client_packages }}'

- name: Check if PHP package is required
  shell: dpkg -s {{ postgresql_client_check_php_package }} | grep 'install ok installed'
  failed_when: php_installed.rc > 1
  register: php_installed
  changed_when: no

- name: Install PHP package (if required)
  apt:
    name: '{{ postgresql_client_php_package }}'
    state: present
  when: php_installed.rc == 0
